name: junghanns
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  auto_size_text: ^3.0.0
  fluttertoast: ^8.2.8
  intl: ^0.18.0
  collection: ^1.18.0
  font_awesome_flutter: ^10.8.0
  http: ^1.2.2
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  location: ^6.0.2
  map_launcher: ^3.5.0
  provider: ^6.1.5
  linear_progress_bar: ^1.1.3
  flutter_spinkit: ^5.2.1
  geolocator: ^12.0.0
  crypto: ^3.0.3
  device_info_plus: ^10.1.2
  shared_preferences: ^2.2.3
  google_maps_flutter: ^2.6.1
  permission_handler: ^11.3.1
  animated_icon: ^0.0.9
  flutter_multi_formatter: ^2.13.7
  sqflite: ^2.3.3+1
  path_provider: ^2.1.4
  firebase_core: ^2.27.0
  firebase_messaging: ^14.7.10
  connectivity_plus: ^5.0.2
  pin_code_text_field: ^1.8.0
  dio: ^5.8.0+1
  just_audio: ^0.9.42
  file_picker: ^8.0.5
  url_launcher: ^6.3.1
  open_file: ^3.5.4
  video_thumbnail: ^0.5.5
  video_player: ^2.9.2
  awesome_dialog: ^3.2.1
  image_gallery_saver: ^2.0.3
  qr_flutter: ^4.1.0
  screenshot: ^2.0.0
  share_plus: ^10.0.0
  socket_io_client: ^3.0.2
  flutter_staggered_grid_view: ^0.7.0
  flutter_local_notifications: ^16.3.1
  flutter_internet_speed_test: ^1.5.0
  speed_test_dart: ^1.0.5+0
  get_it: ^8.0.3
  dotted_border: ^2.1.0
  workmanager: ^0.5.2
  flutter_image_compress: ^2.3.0
  cupertino_icons: ^1.0.2
  firebase_analytics: ^10.10.7
  flutter_svg: ^2.0.9
  web_socket_channel: ^2.0.0
  web_socket_io: ^0.0.4
  accordion: ^2.6.0
  chewie: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/iconApp.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/images/bancos/
  fonts:
    - family: MyriadPro-Bold
      fonts:
        - asset: assets/fonts/MyriadPro-Bold.otf
    - family: MyriadPro-BoldCond
      fonts:
        - asset: assets/fonts/MyriadPro-BoldCond.otf
    - family: MyriadPro-BoldCondit
      fonts:
        - asset: assets/fonts/MyriadPro-BoldCondit.otf
    - family: MyriadPro-Boldit
      fonts:
        - asset: assets/fonts/MyriadPro-Cond.otf
    - family: MyriadPro-Condit
      fonts:
        - asset: assets/fonts/MyriadPro-Condit.otf
    - family: MyriadPro-it
      fonts:
        - asset: assets/fonts/MyriadPro-it.otf
    - family: MyriadPro-Regular
      fonts:
        - asset: assets/fonts/MyriadPro-Regular.otf
    - family: MyriadPro-SemiBold
      fonts:
        - asset: assets/fonts/MyriadPro-SemiBold.otf
    - family: MyriadPro-SemiBoldit
      fonts:
        - asset: assets/fonts/MyriadPro-SemiBoldit.otf