name: junghanns
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  fluttertoast: ^8.0.9
  flutter_staggered_grid_view: ^0.6.1
  intl: ^0.19.0
  font_awesome_flutter: ^9.1.0
  geolocator: ^9.0.0 
  image_picker: ^0.8.3
  image_cropper:
  sqflite: ^2.0.3
  shared_preferences: ^2.0.6
  connectivity_plus: ^2.3.6
  provider: ^6.0.2
  url_launcher: ^6.0.20
  flutter_spinkit: ^5.1.0
  google_maps_flutter: ^2.1.10
  map_launcher: ^2.2.0
  flutter_multi_formatter: ^2.5.8
  pin_code_text_field: ^1.8.0
  location: ^4.4.0
  linear_progress_bar: "^1.1.0"
  path_provider: ^2.0.9
  speed_test_dart: ^1.0.0
  flutter_internet_speed_test: ^1.2.0
  firebase_analytics: ^9.1.2
  firebase_core: ^1.13.1
  firebase_messaging: ^11.2.11
  flutter_local_notifications: ^9.4.0
  device_info_plus: ^6.0.0
  qr_flutter: ^4.0.0
  screenshot: ^3.0.0
  share_plus: ^2.1.4
  permission_handler: ^10.2.0
  awesome_dialog: ^3.1.0
  device_information: ^0.0.4
  mac_address: ^1.0.0
  device_info: ^2.0.0
  image_gallery_saver: ^1.6.7
  flutter_svg: ^2.0.9
  get_it: ^7.2.0
  web_socket_channel: ^2.0.0
  web_socket_io: ^0.0.4
  socket_io_client: ^2.0.3+1
  animated_icon: ^0.0.5
  workmanager: ^0.5.2

  
dependency_overrides:
  firebase_core_platform_interface: 4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"
  

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/iconApp.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
    - assets/images/bancos/
  fonts:
    - family: MyriadPro-Bold
      fonts:
        - asset: assets/fonts/MyriadPro-Bold.otf
    - family: MyriadPro-BoldCond
      fonts:
        - asset: assets/fonts/MyriadPro-BoldCond.otf
    - family: MyriadPro-BoldCondit
      fonts:
        - asset: assets/fonts/MyriadPro-BoldCondit.otf
    - family: MyriadPro-Boldit
      fonts:
        - asset: assets/fonts/MyriadPro-Cond.otf
    - family: MyriadPro-Condit
      fonts:
        - asset: assets/fonts/MyriadPro-Condit.otf
    - family: MyriadPro-it
      fonts:
        - asset: assets/fonts/MyriadPro-it.otf
    - family: MyriadPro-Regular
      fonts:
        - asset: assets/fonts/MyriadPro-Regular.otf
    - family: MyriadPro-SemiBold
      fonts:
        - asset: assets/fonts/MyriadPro-SemiBold.otf
    - family: MyriadPro-SemiBoldit
      fonts:
        - asset: assets/fonts/MyriadPro-SemiBoldit.otf