name: junghanns
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line
    sdk: flutter
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  fluttertoast: ^8.0.9
  flutter_staggered_grid_view: ^0.6.1
  intl: ^0.17.0
  font_awesome_flutter: ^9.1.0
  geolocator: ^9.0.0 
  image_picker: ^0.8.3
  image_cropper:
  sqflite: ^2.0.3
  shared_preferences: ^2.0.6
  connectivity_plus: ^2.3.6
  provider:
  url_launcher: ^6.0.20
  flutter_spinkit: ^5.1.0
  google_maps_flutter: ^2.1.10
  map_launcher: ^2.2.0
  flutter_multi_formatter: ^2.5.8
  pin_code_text_field: ^1.8.0
  flutter_speedtest: ^0.0.2+2
  location: ^4.4.0
  linear_progress_bar: "^1.1.0"
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.10.0"

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/iconApp.jpg"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: MyriadPro-Bold
      fonts:
        - asset: assets/fonts/MyriadPro-Bold.otf
    - family: MyriadPro-BoldCond
      fonts:
        - asset: assets/fonts/MyriadPro-BoldCond.otf
    - family: MyriadPro-BoldCondit
      fonts:
        - asset: assets/fonts/MyriadPro-BoldCondit.otf
    - family: MyriadPro-Boldit
      fonts:
        - asset: assets/fonts/MyriadPro-Cond.otf
    - family: MyriadPro-Condit
      fonts:
        - asset: assets/fonts/MyriadPro-Condit.otf
    - family: MyriadPro-it
      fonts:
        - asset: assets/fonts/MyriadPro-it.otf
    - family: MyriadPro-Regular
      fonts:
        - asset: assets/fonts/MyriadPro-Regular.otf
    - family: MyriadPro-SemiBold
      fonts:
        - asset: assets/fonts/MyriadPro-SemiBold.otf
    - family: MyriadPro-SemiBoldit
      fonts:
        - asset: assets/fonts/MyriadPro-SemiBoldit.otf