name: junghanns
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  auto_size_text: ^3.0.0
  cupertino_icons: ^1.0.2
  http: ^0.13.3
  fluttertoast: ^8.0.9
  flutter_staggered_grid_view: ^0.6.1
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/icons/
  fonts:
    - family: MyriadPro-Bold
      fonts:
        - asset: assets/fonts/MyriadPro-Bold.otf
    - family: MyriadPro-BoldCond
      fonts:
        - asset: assets/fonts/MyriadPro-BoldCond.otf
    - family: MyriadPro-BoldCondit
      fonts:
        - asset: assets/fonts/MyriadPro-BoldCondit.otf
    - family: MyriadPro-Boldit
      fonts:
        - asset: assets/fonts/MyriadPro-Cond.otf
    - family: MyriadPro-Condit
      fonts:
        - asset: assets/fonts/MyriadPro-Condit.otf
    - family: MyriadPro-it
      fonts:
        - asset: assets/fonts/MyriadPro-it.otf
    - family: MyriadPro-Regular
      fonts:
        - asset: assets/fonts/MyriadPro-Regular.otf
    - family: MyriadPro-SemiBold
      fonts:
        - asset: assets/fonts/MyriadPro-SemiBold.otf
    - family: MyriadPro-SemiBoldit
      fonts:
        - asset: assets/fonts/MyriadPro-SemiBoldit.otf